name: Prevent Changes to Specific File

on:
  push:
    branches:
      - "flask"
      - "test"
  pull_request:
    branches:
      - "flask"
      - "test"

jobs:
  block-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Block Changes to Restricted File
        run: |
          echo "Error: Changes to path/to/restricted_file are not allowed."
          exit 1
